version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/onsi/ginkgo/v2
    versions:
    - 2.9.0
    - 2.10.0
    - 2.11.0
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.5