// This file was generated by counterfeiter
// counterfeiter -o ios/iexec/exec_fake.go --fake-name ExecFake ios/iexec/exec.go Exec

package iexec

import "sync"

//ExecFake ...
type ExecFake struct {
	CommandStub        func(string, ...string) Cmd
	commandMutex       sync.RWMutex
	commandArgsForCall []struct {
		arg1 string
		arg2 []string
	}
	commandReturns struct {
		result1 Cmd
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

//Command ...
func (fake *ExecFake) Command(arg1 string, arg2 ...string) Cmd {
	fake.commandMutex.Lock()
	fake.commandArgsForCall = append(fake.commandArgsForCall, struct {
		arg1 string
		arg2 []string
	}{arg1, arg2})
	fake.recordInvocation("Command", []interface{}{arg1, arg2})
	fake.commandMutex.Unlock()
	if fake.CommandStub != nil {
		return fake.CommandStub(arg1, arg2...)
	}
	return fake.commandReturns.result1
}

//CommandCallCount ...
func (fake *ExecFake) CommandCallCount() int {
	fake.commandMutex.RLock()
	defer fake.commandMutex.RUnlock()
	return len(fake.commandArgsForCall)
}

//CommandArgsForCall ...
func (fake *ExecFake) CommandArgsForCall(i int) (string, []string) {
	fake.commandMutex.RLock()
	defer fake.commandMutex.RUnlock()
	return fake.commandArgsForCall[i].arg1, fake.commandArgsForCall[i].arg2
}

//CommandReturns ...
func (fake *ExecFake) CommandReturns(result1 Cmd) {
	fake.CommandStub = nil
	fake.commandReturns = struct {
		result1 Cmd
	}{result1}
}

//Invocations ...
func (fake *ExecFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.commandMutex.RLock()
	defer fake.commandMutex.RUnlock()
	return fake.invocations
}

func (fake *ExecFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ Exec = new(ExecFake)
