#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$( dirname $SCRIPT_DIR )"

# Run tests as vcap user
useradd vcap
chown -R vcap:vcap /tmp
chown -R vcap:vcap $GOPATH

su -c $SCRIPT_DIR/test vcap
