// This file was generated by counterfeiter
package fake

import (
	"sync"

	"github.com/pivotal-cf/cf-redis-broker/consistency"
)

type Checker struct {
	CheckStub        func() error
	checkMutex       sync.RWMutex
	checkArgsForCall []struct{}
	checkReturns     struct {
		result1 error
	}
}

func (fake *Checker) Check() error {
	fake.checkMutex.Lock()
	fake.checkArgsForCall = append(fake.checkArgsForCall, struct{}{})
	fake.checkMutex.Unlock()
	if fake.CheckStub != nil {
		return fake.CheckStub()
	} else {
		return fake.checkReturns.result1
	}
}

func (fake *Checker) CheckCallCount() int {
	fake.checkMutex.RLock()
	defer fake.checkMutex.RUnlock()
	return len(fake.checkArgsForCall)
}

func (fake *Checker) CheckReturns(result1 error) {
	fake.CheckStub = nil
	fake.checkReturns = struct {
		result1 error
	}{result1}
}

var _ consistency.Checker = new(Checker)
