// This file was generated by counterfeiter
package processfakes

import (
	"sync"

	"github.com/pivotal-cf/cf-redis-broker/process"
)

type FakeProcessFinder struct {
	NameStub        func() (string, error)
	nameMutex       sync.RWMutex
	nameArgsForCall []struct{}
	nameReturns     struct {
		result1 string
		result2 error
	}
}

func (fake *FakeProcessFinder) Name() (string, error) {
	fake.nameMutex.Lock()
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct{}{})
	fake.nameMutex.Unlock()
	if fake.NameStub != nil {
		return fake.NameStub()
	} else {
		return fake.nameReturns.result1, fake.nameReturns.result2
	}
}

func (fake *FakeProcessFinder) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeProcessFinder) NameReturns(result1 string, result2 error) {
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

var _ process.ProcessFinder = new(FakeProcessFinder)
