#!/bin/bash

ACTION=$1
shift

case $ACTION in
  start )
    sleep 0.1 ;;
  stop )
    pkill redis-server
    sleep 0.1 ;;
  summary )
    $(ps -ef | grep -q [r]edis-server)
    if [[ $? != 0 ]];
    then
      REDIS_STATUS="not monitored"
    else
      REDIS_STATUS="running"
    fi
    echo "Process 'redis' $REDIS_STATUS" ;;
esac
